# Generated by Django 6.0.5 on 2026-05-30 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to='vault/%Y/%m/')),
                ('file_url', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UNAPPROVED_STORAGE', 'Raw Storage'), ('QUEUED_COMPILE', 'Queued for Compile'), ('LINEAGE_POSTED', 'Posted to Lineage')], default='UNAPPROVED_STORAGE', max_length=20)),
                ('era', models.CharField(choices=[('PROTECTED', 'Protected Era (0-13)'), ('SOVEREIGN', 'Sovereign Era (13+)')], default='SOVEREIGN', max_length=10)),
                ('year', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnnualCompileGate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_year', models.IntegerField()),
                ('is_locked', models.BooleanField(default=False)),
                ('compiled_at', models.DateTimeField(blank=True, null=True)),
                ('item_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compile_gates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-target_year'],
                'unique_together': {('user', 'target_year')},
            },
        ),
    ]
